name: audiobook_manager
description: "An audiobook manager app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  provider: ^6.1.0 # We'll remove this later
  shared_preferences: ^2.3.5 # We'll remove this later
  cupertino_icons: ^1.0.8
  ffmpeg_kit_flutter: ^6.0.3
  file_picker: ^8.1.7
  just_audio: ^0.9.43
  audio_session: ^0.1.23
  uuid: ^4.5.1
  # New dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # For Hive type generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
